USE SCHEMA DEMO1;
ALTER TABLE HELLO_WORLD ADD COLUMN AGE NUMBER;
INSERT INTO HELLO_WORLD 
VALUES 
  ('MS', 'DHONI', 42),
  ('VIRAT', 'KOHLI', 32),
  ('ROHIT', 'SHARMA', 34),
  ('SACHIN', 'TENDULKAR', 48);
